---
# tasks file for role-wordpress
- name: Include ansible wordpress vault
  include_vars: "vars/vault-wordpress.yml"

- name: Create wordpress documentroot {{ web_docroot }}
  become: yes
  file:
    path: "{{ web_docroot }}"
    state: directory
    mode: 0755

- name: Download wordpress and unarchiv
  become: yes
  unarchive:
    src: https://wordpress.org/latest.zip
    remote_src: yes
    dest: "{{ web_docroot }}"

- name: Install pwgen
  apt:
    name: pwgen
    state: latest
    update_cache: yes

- name: Create pw salt
  shell: "/usr/bin/pwgen -s 65 8"
  register: pw_salts
  args:
    executable: /bin/bash

- name: Configure wordpress
  template:
    src: "wp-config.php.j2"
    dest: "{{ web_docroot }}/wp-config.php"
    mode: 0644

- name: Remove sample wp-config
  file:
    path: "{{ web_docroot }}/wp-config-sample.php"
    state: absent

- name: Set correct permissions
  shell: "chown -R {{ web_owner }}:{{ web_group }} {{ web_docroot }}"
  args:
    executable: /bin/bash
#  file:
#    path: "{{ web_docroot }}"
#    owner: "{{ web_owner }}"
#    group: "{{ web_group }}"
#    recurse: yes
